Traceback (most recent call last):
  File "/Users/mackie3/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 622, in _async_poll_for_reply
    msg = await ensure_async(self.kc.shell_channel.get_msg(timeout=new_timeout))
  File "/Users/mackie3/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 85, in ensure_async
    result = await obj
  File "/Users/mackie3/opt/anaconda3/lib/python3.9/site-packages/jupyter_client/asynchronous/channels.py", line 48, in get_msg
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mackie3/opt/anaconda3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/mackie3/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/mackie3/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/mackie3/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/mackie3/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/mackie3/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/Users/mackie3/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 841, in async_execute_cell
    exec_reply = await self.task_poll_for_reply
  File "/Users/mackie3/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 646, in _async_poll_for_reply
    await self._async_handle_timeout(timeout, cell)
  File "/Users/mackie3/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 696, in _async_handle_timeout
    raise CellTimeoutError.error_from_timeout_and_cell(
nbclient.exceptions.CellTimeoutError: A cell timed out while it was being executed, after 30 seconds.
The message was: Cell execution timed out.
Here is a preview of the cell contents:
-------------------
['# set variogram parameters', 'azimuth = 0', 'nugget = V1.parameters[2]', '', '# the major and minor ranges are the same in this example because it is isotropic']
...
['k = 100                     # number of neighboring data points used to estimate a given point ', 'rad = 50000                 # 50 km search radius', '', '# est_SK is the estimate and var_SK is the variance', "est_SK, var_SK = gs.Interpolation.skrige(Pred_grid_xy, df_grid, 'X', 'Y', 'Nbed', k, vario, rad)"]
-------------------

